name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Remplacez par votre version de Node.js

      - name: Install dependencies
        run: |
          cd frontend  # Accédez au dossier frontend
          npm install

      - name: Build application
        run: |
          cd frontend  # Accédez au dossier frontend
          npm run build

      - name: Archive production artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist

      - name: add ssh key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run : |
          echo $SSH_PRIVATE_KEY | ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          PATH_TO_DEPLOYMENT_DIRECTORY: ${{ secrets.PATH_TO_DEPLOYMENT_DIRECTORY }}
        run: |
            scp -r frontend/dist/* $VPS_USER@$VPS_HOST:$PATH_TO_DEPLOYMENT_DIRECTORY
            rm private_key.pem

  start-server:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: add ssh key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo $SSH_PRIVATE_KEY | ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Start server on VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          PATH_TO_DEPLOYMENT_DIRECTORY: ${{ secrets.PATH_TO_DEPLOYMENT_DIRECTORY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem $VPS_USER@$VPS_HOST "cd $PATH_TO_DEPLOYMENT_DIRECTORY && git checkout . && git pull && npm install && pm2 restart all"
          rm private_key.pem
